# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-30 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', models.ManyToManyField(to='text_parser.Text')),
            ],
        ),
    ]
